export const locations20 = [
  "Best Advocate | Best Lawyers in Noida Sector 7 for Loan settlement",
  "Best Advocate | Best Lawyers in Shastri Park for Loan settlement",
  "Best Advocate | Best Lawyers in Margao for Loan settlement",
  "Best Advocate | Best Lawyers in Peeragarhi for Loan settlement",
  "Best Advocate | Best Lawyers in Paschim Vihar for Loan settlement",
  "Best Advocate | Best Lawyers in Yamuna Vihar Depot for Loan settlement",
  "Best Advocate | Best Lawyers in Sirsa for Loan settlement",
  "Best Advocate | Best Lawyers in Vaishali Sector 8 for Loan settlement",
  "Best Advocate | Best Lawyers in Kashmere Gate ISBT for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 69 for Loan settlement",

  "Best Advocate | Best Lawyers in Punjabi Bagh for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 129 for Loan settlement",
  "Best Advocate | Best Lawyers in Siddharth Vihar Sector 1 for Loan settlement",
  "Best Advocate | Best Lawyers in Kannur for Loan settlement",
  "Best Advocate | Best Lawyers in Delhi for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad Sector 37 for Loan settlement",
  "Best Advocate | Best Lawyers in Baba Colony for Loan settlement",
  "Best Advocate | Best Lawyers in Pitampura for Loan settlement",
  "Best Advocate | Best Lawyers in Indira Gandhi Indoor Stadium for Loan settlement",
  "Best Advocate | Best Lawyers in Gyan Khand 4 for Loan settlement",

  "Best Advocate | Best Lawyers in Ghaziabad Bus Stand for Loan settlement",
  "Best Advocate | Best Lawyers in Raipur for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 75 for Loan settlement",
  "Best Advocate | Best Lawyers in Dwarka Sector 10 Metro for Loan settlement",
  "Best Advocate | Best Lawyers in Samba for Loan settlement",
  "Best Advocate | Best Lawyers in Nanded for Loan settlement",
  "Best Advocate | Best Lawyers in Tonk for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 128 for Loan settlement",
  "Best Advocate | Best Lawyers in Govindpuram Sector 4 for Loan settlement",
  "Best Advocate | Best Lawyers in Basti for Loan settlement",

  "Best Advocate | Best Lawyers in Noida Sector 27 for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 93A for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 25 for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 95 for Loan settlement",
  "Best Advocate | Best Lawyers in Lakhimpur Kheri for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 62 for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad Sector 13 for Loan settlement",
  "Best Advocate | Best Lawyers in Sri Potti Sriramulu Nellore for Loan settlement",
  "Best Advocate | Best Lawyers in Preet Vihar for Loan settlement",
  "Best Advocate | Best Lawyers in Jalna for Loan settlement",

  "Best Advocate | Best Lawyers in Khandwa for Loan settlement",
  "Best Advocate | Best Lawyers in Thoothukudi for Loan settlement",
  "Best Advocate | Best Lawyers in Bikaner for Loan settlement",
  "Best Advocate | Best Lawyers in Sanjay Nagar Sector 3 for Loan settlement",
  "Best Advocate | Best Lawyers in Silchar for Loan settlement",
  "Best Advocate | Best Lawyers in Nand Nagri for Loan settlement",
  "Best Advocate | Best Lawyers in Kandhamal for Loan settlement",
  "Best Advocate | Best Lawyers in Kapurthala for Loan settlement",
  "Best Advocate | Best Lawyers in Trilokpuri Metro for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 41 for Loan settlement",

  "Best Advocate | Best Lawyers in Gurugram Sector 44 for Loan settlement",
  "Best Advocate | Best Lawyers in Sikar for Loan settlement",
  "Best Advocate | Best Lawyers in Bhiwani for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 8 for Loan settlement",
  "Best Advocate | Best Lawyers in Punjab for Loan settlement",
  "Best Advocate | Best Lawyers in Dimapur for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 43 for Loan settlement",
  "Best Advocate | Best Lawyers in Dundahera for Loan settlement",
  "Best Advocate | Best Lawyers in Balaghat for Loan settlement",
  "Best Advocate | Best Lawyers in Wayanad for Loan settlement",

  "Best Advocate | Best Lawyers in Noida Sector 106 for Loan settlement",
  "Best Advocate | Best Lawyers in Surajpur for Loan settlement",
  "Best Advocate | Best Lawyers in Knowledge Park 5 for Loan settlement",
  "Best Advocate | Best Lawyers in Imphal East for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 12 for Loan settlement",
  "Best Advocate | Best Lawyers in Okhla Bird Sanctuary for Loan settlement",
  "Best Advocate | Best Lawyers in Lalitpur for Loan settlement",
  "Best Advocate | Best Lawyers in Sultanpur for Loan settlement",
  "Best Advocate | Best Lawyers in Garhwal (Pauri Garhwal) for Loan settlement",
  "Best Advocate | Best Lawyers in Vaishali for Loan settlement",

  "Best Advocate | Best Lawyers in Chittagong for Loan settlement",
  "Best Advocate | Best Lawyers in Rajnandgaon for Loan settlement",
  "Best Advocate | Best Lawyers in Kargil for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Extension Sector 25 for Loan settlement",
  "Best Advocate | Best Lawyers in New Friends Colony for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 56 for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Delta 1 for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Extension Sector 4 for Loan settlement",
  "Best Advocate | Best Lawyers in Salem for Loan settlement",
  "Best Advocate | Best Lawyers in Paschim Vihar East for Loan settlement",

  "Best Advocate | Best Lawyers in Dwarka Sector 9 for Loan settlement",
  "Best Advocate | Best Lawyers in Rampur for Loan settlement",
  "Best Advocate | Best Lawyers in Coimbatore for Loan settlement",
  "Best Advocate | Best Lawyers in Bijapur for Loan settlement",
  "Best Advocate | Best Lawyers in Sector 12 Vasundhara for Loan settlement",
  "Best Advocate | Best Lawyers in Gazipur for Loan settlement",
  "Best Advocate | Best Lawyers in Malviya Nagar for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 86 for Loan settlement",
  "Best Advocate | Best Lawyers in Rohini Sector 13 for Loan settlement",
  "Best Advocate | Best Lawyers in Wave City Harmony Floors for Loan settlement",

  "Best Advocate | Best Lawyers in Rohini Sector 3 for Loan settlement",
  "Best Advocate | Best Lawyers in Rockhampton for Loan settlement",
  "Best Advocate | Best Lawyers in Kohima for Loan settlement",
  "Best Advocate | Best Lawyers in Sector 10 Vasundhara for Loan settlement",
  "Best Advocate | Best Lawyers in Vikarabad for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Beta 1 for Loan settlement",
  "Best Advocate | Best Lawyers in Burhanpur for Loan settlement",
  "Best Advocate | Best Lawyers in Muzaffarnagar for Loan settlement",
  "Best Advocate | Best Lawyers in Uttara Kannada for Loan settlement",
  "Best Advocate | Best Lawyers in Janakpuri for Loan settlement"
];
