export const locations13 = [
  "Best Advocate | Best Lawyers in Okhla for Loan settlement",
  "Best Advocate | Best Lawyers in Uttarakhand for Loan settlement",
  "Best Advocate | Best Lawyers in Mohan Nagar Industrial Area for Loan settlement",
  "Best Advocate | Best Lawyers in Kottayam for Loan settlement",
  "Best Advocate | Best Lawyers in Jalpaiguri for Loan settlement",
  "Best Advocate | Best Lawyers in Murshidabad for Loan settlement",
  "Best Advocate | Best Lawyers in Sector Theta 3 for Loan settlement",
  "Best Advocate | Best Lawyers in Dausa for Loan settlement",
  "Best Advocate | Best Lawyers in Kanpur for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad for Loan settlement",

  "Best Advocate | Best Lawyers in Noida Sector 148 for Loan settlement",
  "Best Advocate | Best Lawyers in Howrah for Loan settlement",
  "Best Advocate | Best Lawyers in Kendujhar for Loan settlement",
  "Best Advocate | Best Lawyers in Malkangiri for Loan settlement",
  "Best Advocate | Best Lawyers in Siddipet for Loan settlement",
  "Best Advocate | Best Lawyers in Jorhat for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 15 for Loan settlement",
  "Best Advocate | Best Lawyers in Shillong for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 9A for Loan settlement",
  "Best Advocate | Best Lawyers in Raj Nagar Sector 3 for Loan settlement",

  "Best Advocate | Best Lawyers in Tiruvannamalai for Loan settlement",
  "Best Advocate | Best Lawyers in Naharlagun for Loan settlement",
  "Best Advocate | Best Lawyers in Gadchiroli for Loan settlement",
  "Best Advocate | Best Lawyers in Baramulla for Loan settlement",
  "Best Advocate | Best Lawyers in Patparganj for Loan settlement",
  "Best Advocate | Best Lawyers in Jasola Vihar for Loan settlement",
  "Best Advocate | Best Lawyers in Sonitpur for Loan settlement",
  "Best Advocate | Best Lawyers in Ballarat for Loan settlement",
  "Best Advocate | Best Lawyers in Hazaribagh for Loan settlement",
  "Best Advocate | Best Lawyers in North Garo Hills for Loan settlement"
];

export const locations14 = [
  "Best Advocate | Best Lawyers in Mohan Estate for Loan settlement",
  "Best Advocate | Best Lawyers in Kingsway Camp for Loan settlement",
  "Best Advocate | Best Lawyers in Central Coast for Loan settlement",
  "Best Advocate | Best Lawyers in Sirmaur for Loan settlement",
  "Best Advocate | Best Lawyers in Kheda for Loan settlement",
  "Best Advocate | Best Lawyers in Barmer for Loan settlement",
  "Best Advocate | Best Lawyers in Guntur for Loan settlement",
  "Best Advocate | Best Lawyers in Sector 64 Indirapuram for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad Sector 33 for Loan settlement",
  "Best Advocate | Best Lawyers in Krishna for Loan settlement",

  "Best Advocate | Best Lawyers in Hoshangabad for Loan settlement",
  "Best Advocate | Best Lawyers in North 24 Parganas for Loan settlement",
  "Best Advocate | Best Lawyers in Cuttack for Loan settlement",
  "Best Advocate | Best Lawyers in Parliament for Loan settlement",
  "Best Advocate | Best Lawyers in Najafgarh for Loan settlement",
  "Best Advocate | Best Lawyers in Etah for Loan settlement",
  "Best Advocate | Best Lawyers in Indirapuram Shakti Khand 1 for Loan settlement",
  "Best Advocate | Best Lawyers in New Delhi for Loan settlement",
  "Best Advocate | Best Lawyers in Old Delhi Railway Station for Loan settlement",
  "Best Advocate | Best Lawyers in Mon for Loan settlement",

  "Best Advocate | Best Lawyers in Kurung Kumey for Loan settlement",
  "Best Advocate | Best Lawyers in Wollongong for Loan settlement",
  "Best Advocate | Best Lawyers in Ramprastha for Loan settlement",
  "Best Advocate | Best Lawyers in Kaushambi for Loan settlement",
  "Best Advocate | Best Lawyers in Mancherial for Loan settlement",
  "Best Advocate | Best Lawyers in Dibrugarh for Loan settlement",
  "Best Advocate | Best Lawyers in Datia for Loan settlement",
  "Best Advocate | Best Lawyers in Gujarat for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 24 for Loan settlement",
  "Best Advocate | Best Lawyers in Sirohi for Loan settlement",
  "Best Advocate | Best Lawyers in Shopian for Loan settlement"
];
