export const locations5 = [
  "Best Advocate | Best Lawyers in Tirap for Loan settlement",
  "Best Advocate | Best Lawyers in Fazilka for Loan settlement",
  "Best Advocate | Best Lawyers in Khanpur for Loan settlement",
  "Best Advocate | Best Lawyers in Jamnagar for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 4 for Loan settlement",
  "Best Advocate | Best Lawyers in Karampura for Loan settlement",
  "Best Advocate | Best Lawyers in Dasna Village for Loan settlement",
  "Best Advocate | Best Lawyers in Chandigarh for Loan settlement",
  "Best Advocate | Best Lawyers in Govindpuram Sector 2 for Loan settlement",
  "Best Advocate | Best Lawyers in Goalpara for Loan settlement",

  "Best Advocate | Best Lawyers in Thoubal for Loan settlement",
  "Best Advocate | Best Lawyers in Hamirpur for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 18 for Loan settlement",
  "Best Advocate | Best Lawyers in Hoshiarpur for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 144 for Loan settlement",
  "Best Advocate | Best Lawyers in Shastri Nagar Block B for Loan settlement",
  "Best Advocate | Best Lawyers in Tiruchirappalli for Loan settlement",
  "Best Advocate | Best Lawyers in Dindori for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 26 for Loan settlement",
  "Best Advocate | Best Lawyers in AIIMS Metro for Loan settlement",

  "Best Advocate | Best Lawyers in Srinagar for Loan settlement",
  "Best Advocate | Best Lawyers in Kanchipuram for Loan settlement",
  "Best Advocate | Best Lawyers in Shastri Nagar Block D for Loan settlement",
  "Best Advocate | Best Lawyers in Govindpuram Sector 8 for Loan settlement",
  "Best Advocate | Best Lawyers in Dhamtari for Loan settlement",
  "Best Advocate | Best Lawyers in Khargone for Loan settlement",
  "Best Advocate | Best Lawyers in Ramgarh for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 71 for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 9 for Loan settlement",
  "Best Advocate | Best Lawyers in Sahibganj for Loan settlement",

  "Best Advocate | Best Lawyers in Kavi Nagar Sector 10 for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 31 for Loan settlement",
  "Best Advocate | Best Lawyers in Churu for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Beta 2 for Loan settlement",
  "Best Advocate | Best Lawyers in Vaishali Sector 4 for Loan settlement",
  "Best Advocate | Best Lawyers in Dasna Industrial Area for Loan settlement",
  "Best Advocate | Best Lawyers in Mandi for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad Sector 31 for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 149 for Loan settlement",
  "Best Advocate | Best Lawyers in Upper Subansiri for Loan settlement"
];

export const locations6 = [
  "Best Advocate | Best Lawyers in Gurugram Sector 22A for Loan settlement",
  "Best Advocate | Best Lawyers in Haridwar for Loan settlement",
  "Best Advocate | Best Lawyers in Poonch for Loan settlement",
  "Best Advocate | Best Lawyers in Sonbhadra for Loan settlement",
  "Best Advocate | Best Lawyers in Birbhum for Loan settlement",
  "Best Advocate | Best Lawyers in Meerut for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 134 for Loan settlement",
  "Best Advocate | Best Lawyers in Madhya Pradesh for Loan settlement",
  "Best Advocate | Best Lawyers in Jaipur for Loan settlement",
  "Best Advocate | Best Lawyers in Khajuri Khas for Loan settlement",

  "Best Advocate | Best Lawyers in Dhanbad for Loan settlement",
  "Best Advocate | Best Lawyers in Jharsuguda for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 39 for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 155 for Loan settlement",
  "Best Advocate | Best Lawyers in Mizoram for Loan settlement",
  "Best Advocate | Best Lawyers in Gurgaon for Loan settlement",
  "Best Advocate | Best Lawyers in Varanasi for Loan settlement",
  "Best Advocate | Best Lawyers in Jehanabad for Loan settlement",
  "Best Advocate | Best Lawyers in Sector Zeta 4 for Loan settlement",
  "Best Advocate | Best Lawyers in Rewari for Loan settlement",

  "Best Advocate | Best Lawyers in Patan for Loan settlement",
  "Best Advocate | Best Lawyers in Jodhpur for Loan settlement",
  "Best Advocate | Best Lawyers in Rohini Sector 24 for Loan settlement",
  "Best Advocate | Best Lawyers in Dwarka Mor for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 12 for Loan settlement",
  "Best Advocate | Best Lawyers in Gaya for Loan settlement",
  "Best Advocate | Best Lawyers in Vijayapura for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 60 for Loan settlement",
  "Best Advocate | Best Lawyers in Sidhi for Loan settlement",
  "Best Advocate | Best Lawyers in Sant Ravidas Nagar for Loan settlement",

  "Best Advocate | Best Lawyers in Leh for Loan settlement",
  "Best Advocate | Best Lawyers in Mumbai City for Loan settlement",
  "Best Advocate | Best Lawyers in Adarsh Nagar for Loan settlement",
  "Best Advocate | Best Lawyers in Punjabi Bagh West for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad Sector 35 for Loan settlement",
  "Best Advocate | Best Lawyers in Shahdara Depot for Loan settlement",
  "Best Advocate | Best Lawyers in Dumka for Loan settlement",
  "Best Advocate | Best Lawyers in Bhadradri Kothagudem for Loan settlement",
  "Best Advocate | Best Lawyers in Imphal for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 114 for Loan settlement"
];

export const locations7 = [
  "Best Advocate | Best Lawyers in Hindon Air Force Station for Loan settlement",
  "Best Advocate | Best Lawyers in Wave Executive Floors for Loan settlement",
  "Best Advocate | Best Lawyers in Wave City Sector 8 for Loan settlement",
  "Best Advocate | Best Lawyers in Jatwara for Loan settlement",
  "Best Advocate | Best Lawyers in Mackay for Loan settlement",
  "Best Advocate | Best Lawyers in Mathura for Loan settlement",
  "Best Advocate | Best Lawyers in Sector 7 Vasundhara for Loan settlement",
  "Best Advocate | Best Lawyers in Koraput for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad Sector 17 for Loan settlement",
  "Best Advocate | Best Lawyers in Muradnagar Industrial Area for Loan settlement",

  "Best Advocate | Best Lawyers in Surajpur for Loan settlement",
  "Best Advocate | Best Lawyers in Junagadh for Loan settlement",
  "Best Advocate | Best Lawyers in Nehru Place for Loan settlement",
  "Best Advocate | Best Lawyers in Punjabi Bagh Metro for Loan settlement",
  "Best Advocate | Best Lawyers in Pandav Nagar for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 100 for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 28 for Loan settlement",
  "Best Advocate | Best Lawyers in Shaheen Bagh for Loan settlement",
  "Best Advocate | Best Lawyers in Belagavi for Loan settlement",
  "Best Advocate | Best Lawyers in Narela for Loan settlement",

  "Best Advocate | Best Lawyers in Udaipur for Loan settlement",
  "Best Advocate | Best Lawyers in Crossing Republik Ajnara Gen X for Loan settlement",
  "Best Advocate | Best Lawyers in Railway Colony for Loan settlement",
  "Best Advocate | Best Lawyers in Una for Loan settlement",
  "Best Advocate | Best Lawyers in Gyan Khand 1 for Loan settlement",
  "Best Advocate | Best Lawyers in Karampura Industrial Area for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad Sector 15 for Loan settlement",
  "Best Advocate | Best Lawyers in Raigad for Loan settlement",
  "Best Advocate | Best Lawyers in Sector Xu 2 for Loan settlement",
  "Best Advocate | Best Lawyers in Vaibhav Khand for Loan settlement",

  "Best Advocate | Best Lawyers in Crossings Republic Gaur Global Village for Loan settlement",
  "Best Advocate | Best Lawyers in Nalgonda for Loan settlement",
  "Best Advocate | Best Lawyers in Bhavnagar for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 21 for Loan settlement",
  "Best Advocate | Best Lawyers in Purulia for Loan settlement",
  "Best Advocate | Best Lawyers in Karaikal for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 65 for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Omicron 2 for Loan settlement",
  "Best Advocate | Best Lawyers in Doda for Loan settlement",
  "Best Advocate | Best Lawyers in Tronica City Sector D for Loan settlement"
];

export const locations8 = [
  "Best Advocate | Best Lawyers in Panipat for Loan settlement",
  "Best Advocate | Best Lawyers in Gondia for Loan settlement",
  "Best Advocate | Best Lawyers in Mahbubabad for Loan settlement",
  "Best Advocate | Best Lawyers in Vasundhara Sector 1 for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 35 for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 31 for Loan settlement",
  "Best Advocate | Best Lawyers in Indraprastha Park for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 37 for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Delta 4 for Loan settlement",
  "Best Advocate | Best Lawyers in Vasant Kunj Bus Stand for Loan settlement",

  "Best Advocate | Best Lawyers in Siddharth Vihar Sector 4 for Loan settlement",
  "Best Advocate | Best Lawyers in Nadia for Loan settlement",
  "Best Advocate | Best Lawyers in Purba Medinipur for Loan settlement",
  "Best Advocate | Best Lawyers in Indore for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 37C for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 6 for Loan settlement",
  "Best Advocate | Best Lawyers in Jalandhar for Loan settlement",
  "Best Advocate | Best Lawyers in Niti Bagh Colony for Loan settlement",
  "Best Advocate | Best Lawyers in East Khasi Hills for Loan settlement",
  "Best Advocate | Best Lawyers in Panchkula for Loan settlement",

  "Best Advocate | Best Lawyers in Srikakulam for Loan settlement",
  "Best Advocate | Best Lawyers in Hooghly for Loan settlement",
  "Best Advocate | Best Lawyers in Seraikela-Kharsawan for Loan settlement",
  "Best Advocate | Best Lawyers in Yamuna Expressway Sector 24 for Loan settlement",
  "Best Advocate | Best Lawyers in Bhopal for Loan settlement",
  "Best Advocate | Best Lawyers in Upper Siang for Loan settlement",
  "Best Advocate | Best Lawyers in Washim for Loan settlement",
  "Best Advocate | Best Lawyers in Rajdhani Park for Loan settlement",
  "Best Advocate | Best Lawyers in Sector Chi 3 for Loan settlement",
  "Best Advocate | Best Lawyers in Kolkata for Loan settlement",

  "Best Advocate | Best Lawyers in West Champaran for Loan settlement",
  "Best Advocate | Best Lawyers in Andaman and Nicobar Islands for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 42 for Loan settlement",
  "Best Advocate | Best Lawyers in Seemapuri for Loan settlement",
  "Best Advocate | Best Lawyers in Paharganj for Loan settlement",
  "Best Advocate | Best Lawyers in Udham Singh Nagar for Loan settlement",
  "Best Advocate | Best Lawyers in Nalbari for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 10A for Loan settlement",
  "Best Advocate | Best Lawyers in Ecotech 5 for Loan settlement",
  "Best Advocate | Best Lawyers in Shakarpur for Loan settlement"
];
