export const locations9 = [
  "Best Advocate | Best Lawyers in Geraldton for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad Sector 11 for Loan settlement",
  "Best Advocate | Best Lawyers in ITO for Loan settlement",
  "Best Advocate | Best Lawyers in Inderlok for Loan settlement",
  "Best Advocate | Best Lawyers in Hyderabad for Loan settlement",
  "Best Advocate | Best Lawyers in Nuapada for Loan settlement",
  "Best Advocate | Best Lawyers in Thiruvananthapuram for Loan settlement",
  "Best Advocate | Best Lawyers in Senapati for Loan settlement",
  "Best Advocate | Best Lawyers in Burari for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 122 for Loan settlement",

  "Best Advocate | Best Lawyers in Brij Vihar for Loan settlement",
  "Best Advocate | Best Lawyers in Tilak Nagar for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 13 for Loan settlement",
  "Best Advocate | Best Lawyers in Jajpur for Loan settlement",
  "Best Advocate | Best Lawyers in Kolar for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 7 for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 37 for Loan settlement",
  "Best Advocate | Best Lawyers in Alipurduar for Loan settlement",
  "Best Advocate | Best Lawyers in Banka for Loan settlement",
  "Best Advocate | Best Lawyers in Delhi University - North Campus for Loan settlement",

  "Best Advocate | Best Lawyers in Bhopal for Loan settlement",
  "Best Advocate | Best Lawyers in Shastri Nagar Block A for Loan settlement",
  "Best Advocate | Best Lawyers in Chhattarpur Temple for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Omicron 1 for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 15 for Loan settlement",
  "Best Advocate | Best Lawyers in Kutch for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Omicron 3 for Loan settlement",
  "Best Advocate | Best Lawyers in Indirapuram Nyay Khand 3 for Loan settlement",
  "Best Advocate | Best Lawyers in Sarita Vihar for Loan settlement",
  "Best Advocate | Best Lawyers in Bagalkote for Loan settlement",

  "Best Advocate | Best Lawyers in Nehrunagar Sector 3 for Loan settlement",
  "Best Advocate | Best Lawyers in Dungarpur for Loan settlement",
  "Best Advocate | Best Lawyers in Ram Vihar for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad Sector 27 for Loan settlement",
  "Best Advocate | Best Lawyers in Gir Somnath for Loan settlement",
  "Best Advocate | Best Lawyers in Shimoga for Loan settlement",
  "Best Advocate | Best Lawyers in Jamia Millia Islamia for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 38 for Loan settlement",
  "Best Advocate | Best Lawyers in Karur for Loan settlement",
  "Best Advocate | Best Lawyers in Champhai for Loan settlement"
];

export const locations10 = [
  "Best Advocate | Best Lawyers in Kavi Nagar Sector 13 for Loan settlement",
  "Best Advocate | Best Lawyers in North Tripura for Loan settlement",
  "Best Advocate | Best Lawyers in Chhota Udepur for Loan settlement",
  "Best Advocate | Best Lawyers in Jaunpur for Loan settlement",
  "Best Advocate | Best Lawyers in Madhepura for Loan settlement",
  "Best Advocate | Best Lawyers in Vaishali Sector 6 for Loan settlement",
  "Best Advocate | Best Lawyers in Jammu and Kashmir for Loan settlement",
  "Best Advocate | Best Lawyers in Medchal–Malkajgiri for Loan settlement",
  "Best Advocate | Best Lawyers in Tirunelveli for Loan settlement",
  "Best Advocate | Best Lawyers in Karimganj for Loan settlement",

  "Best Advocate | Best Lawyers in Wave City Sector 3 for Loan settlement",
  "Best Advocate | Best Lawyers in Lower Subansiri for Loan settlement",
  "Best Advocate | Best Lawyers in Anjaw for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 23 for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 25 for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 10 for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 59 for Loan settlement",
  "Best Advocate | Best Lawyers in Tawang for Loan settlement",
  "Best Advocate | Best Lawyers in Delhi Cantonment Bus Terminal for Loan settlement",
  "Best Advocate | Best Lawyers in Bargarh for Loan settlement",

  "Best Advocate | Best Lawyers in Sivaganga for Loan settlement",
  "Best Advocate | Best Lawyers in Chamba for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad Sector 36 for Loan settlement",
  "Best Advocate | Best Lawyers in Bhikaji Cama Place for Loan settlement",
  "Best Advocate | Best Lawyers in Vaishali Sector 5 for Loan settlement",
  "Best Advocate | Best Lawyers in Ramprastha Colony for Loan settlement",
  "Best Advocate | Best Lawyers in Rajanna Sircilla for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 40 for Loan settlement",
  "Best Advocate | Best Lawyers in Raj Nagar Sector 6 for Loan settlement",
  "Best Advocate | Best Lawyers in Gorakhpur for Loan settlement",

  "Best Advocate | Best Lawyers in Modinagar Railway Station for Loan settlement",
  "Best Advocate | Best Lawyers in Mahipalpur for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Tau 1 for Loan settlement",
  "Best Advocate | Best Lawyers in Barabanki for Loan settlement",
  "Best Advocate | Best Lawyers in Kirbi Place for Loan settlement",
  "Best Advocate | Best Lawyers in Nehru Enclave for Loan settlement",
  "Best Advocate | Best Lawyers in Serchhip for Loan settlement",
  "Best Advocate | Best Lawyers in Perambalur for Loan settlement",
  "Best Advocate | Best Lawyers in Peren for Loan settlement",
  "Best Advocate | Best Lawyers in Red Fort (Lal Qila) for Loan settlement"
];

export const locations11 = [
  "Best Advocate | Best Lawyers in IGI Airport Metro for Loan settlement",
  "Best Advocate | Best Lawyers in Kamareddy for Loan settlement",
  "Best Advocate | Best Lawyers in Namakkal for Loan settlement",
  "Best Advocate | Best Lawyers in Central Delhi for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 47 for Loan settlement",
  "Best Advocate | Best Lawyers in Sanjay Nagar Sector 5 for Loan settlement",
  "Best Advocate | Best Lawyers in Dhubri for Loan settlement",
  "Best Advocate | Best Lawyers in Fatehabad for Loan settlement",
  "Best Advocate | Best Lawyers in Sundargarh for Loan settlement",
  "Best Advocate | Best Lawyers in Deoria for Loan settlement",

  "Best Advocate | Best Lawyers in Munger for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Gamma 1 for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 93 for Loan settlement",
  "Best Advocate | Best Lawyers in Tronica City Sector A for Loan settlement",
  "Best Advocate | Best Lawyers in Laxmi Nagar Bus Depot for Loan settlement",
  "Best Advocate | Best Lawyers in Bathinda for Loan settlement",
  "Best Advocate | Best Lawyers in Visakhapatnam for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 118 for Loan settlement",
  "Best Advocate | Best Lawyers in Osmanabad for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Zeta 1 for Loan settlement",

  "Best Advocate | Best Lawyers in Noida Sector 57 for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 139 for Loan settlement",
  "Best Advocate | Best Lawyers in Belgaum for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 22B for Loan settlement",
  "Best Advocate | Best Lawyers in North East Delhi for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad Sector 22 for Loan settlement",
  "Best Advocate | Best Lawyers in Hindon Residential Area for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 4 for Loan settlement",
  "Best Advocate | Best Lawyers in Wave City Sector 7 for Loan settlement",
  "Best Advocate | Best Lawyers in Lohardaga for Loan settlement",

  "Best Advocate | Best Lawyers in Vikaspuri for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Alpha 1 for Loan settlement",
  "Best Advocate | Best Lawyers in Kamrup Metropolitan for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Sigma 4 for Loan settlement",
  "Best Advocate | Best Lawyers in Mumbai for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 11 for Loan settlement",
  "Best Advocate | Best Lawyers in Sindhudurg for Loan settlement",
  "Best Advocate | Best Lawyers in Basti for Loan settlement",
  "Best Advocate | Best Lawyers in Morti Extension for Loan settlement",
  "Best Advocate | Best Lawyers in Morena for Loan settlement"
];

export const locations12 = [
  "Best Advocate | Best Lawyers in Bilaspur for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Extension Sector 10 for Loan settlement",
  "Best Advocate | Best Lawyers in Jaisalmer for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 38 for Loan settlement",
  "Best Advocate | Best Lawyers in Narayanpur for Loan settlement",
  "Best Advocate | Best Lawyers in Firozabad for Loan settlement",
  "Best Advocate | Best Lawyers in Jabalpur for Loan settlement",
  "Best Advocate | Best Lawyers in Bengaluru Rural for Loan settlement",
  "Best Advocate | Best Lawyers in Thrissur for Loan settlement",
  "Best Advocate | Best Lawyers in Kalahandi for Loan settlement",

  "Best Advocate | Best Lawyers in Chitradurga for Loan settlement",
  "Best Advocate | Best Lawyers in Bareilly for Loan settlement",
  "Best Advocate | Best Lawyers in Mahasamund for Loan settlement",
  "Best Advocate | Best Lawyers in Shadipur Metro for Loan settlement",
  "Best Advocate | Best Lawyers in Sawai Madhopur for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 108 for Loan settlement",
  "Best Advocate | Best Lawyers in Kochi for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 101 for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 24 for Loan settlement",
  "Best Advocate | Best Lawyers in Kolasib for Loan settlement",

  "Best Advocate | Best Lawyers in Vasundhara Sector 2 for Loan settlement",
  "Best Advocate | Best Lawyers in Shadipur for Loan settlement",
  "Best Advocate | Best Lawyers in Pulwama for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 94 for Loan settlement",
  "Best Advocate | Best Lawyers in Anand Vihar ISBT for Loan settlement",
  "Best Advocate | Best Lawyers in Leh for Loan settlement",
  "Best Advocate | Best Lawyers in Indirapuram Abhay Khand 1 for Loan settlement",
  "Best Advocate | Best Lawyers in Yadgir for Loan settlement",
  "Best Advocate | Best Lawyers in Dhar for Loan settlement",
  "Best Advocate | Best Lawyers in Majnu Ka Tilla for Loan settlement",

  "Best Advocate | Best Lawyers in Tengnoupal for Loan settlement",
  "Best Advocate | Best Lawyers in Khagaria for Loan settlement",
  "Best Advocate | Best Lawyers in Jalaun for Loan settlement",
  "Best Advocate | Best Lawyers in Shahdara for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 2 for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 2 for Loan settlement",
  "Best Advocate | Best Lawyers in Kheri for Loan settlement",
  "Best Advocate | Best Lawyers in Simdega for Loan settlement",
  "Best Advocate | Best Lawyers in Koriya for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 34 for Loan settlement"
];
