export const locations23 = [
  "Best Advocate | Best Lawyers in Chandrapur for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 9 for Loan settlement",
  "Best Advocate | Best Lawyers in Lakhimpur for Loan settlement",
  "Best Advocate | Best Lawyers in Vasundhara Sector 10 for Loan settlement",
  "Best Advocate | Best Lawyers in Sahibabad for Loan settlement",
  "Best Advocate | Best Lawyers in Nandurbar for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 1 for Loan settlement",
  "Best Advocate | Best Lawyers in Sanjay Nagar Sector 4 for Loan settlement",
  "Best Advocate | Best Lawyers in Kolkata for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 28 for Loan settlement",

  "Best Advocate | Best Lawyers in Malda for Loan settlement",
  "Best Advocate | Best Lawyers in Rajiv Chowk for Loan settlement",
  "Best Advocate | Best Lawyers in Diu for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 93B for Loan settlement",
  "Best Advocate | Best Lawyers in Satyawati College for Loan settlement",
  "Best Advocate | Best Lawyers in Vasundhara Sector 3 for Loan settlement",
  "Best Advocate | Best Lawyers in Ratnagiri for Loan settlement",
  "Best Advocate | Best Lawyers in Abupur for Loan settlement",
  "Best Advocate | Best Lawyers in Mysore for Loan settlement",
  "Best Advocate | Best Lawyers in Tumakuru for Loan settlement",

  "Best Advocate | Best Lawyers in Golaghat for Loan settlement",
  "Best Advocate | Best Lawyers in Sabarkantha for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Gamma 2 for Loan settlement",
  "Best Advocate | Best Lawyers in Himachal Pradesh for Loan settlement",
  "Best Advocate | Best Lawyers in Kokrajhar for Loan settlement",
  "Best Advocate | Best Lawyers in Jalore for Loan settlement",
  "Best Advocate | Best Lawyers in Lahaul and Spiti for Loan settlement",
  "Best Advocate | Best Lawyers in Niti Khand 2 for Loan settlement",
  "Best Advocate | Best Lawyers in Tamil Nadu for Loan settlement",
  "Best Advocate | Best Lawyers in Sant Kabir Nagar for Loan settlement",

  "Best Advocate | Best Lawyers in Sundar Nagar for Loan settlement",
  "Best Advocate | Best Lawyers in Rajkot for Loan settlement",
  "Best Advocate | Best Lawyers in Shamli for Loan settlement",
  "Best Advocate | Best Lawyers in Noida Sector 107 for Loan settlement",
  "Best Advocate | Best Lawyers in Dibang Valley for Loan settlement",
  "Best Advocate | Best Lawyers in Patel Chowk for Loan settlement",
  "Best Advocate | Best Lawyers in Yamuna Bank for Loan settlement",
  "Best Advocate | Best Lawyers in Techzone 2 for Loan settlement",
  "Best Advocate | Best Lawyers in Greater Noida Sector Alpha 2 for Loan settlement",

  "Best Advocate | Best Lawyers in Cachar for Loan settlement",
  "Best Advocate | Best Lawyers in Dhenkanal for Loan settlement",
  "Best Advocate | Best Lawyers in Katni for Loan settlement",
  "Best Advocate | Best Lawyers in Gaur City 2 for Loan settlement",
  "Best Advocate | Best Lawyers in Shalimar Garden Ext 1 for Loan settlement",
  "Best Advocate | Best Lawyers in Faridabad Bus Stand for Loan settlement",
  "Best Advocate | Best Lawyers in Vivek Vihar for Loan settlement",
  "Best Advocate | Best Lawyers in Gopalganj for Loan settlement",
  "Best Advocate | Best Lawyers in South Goa for Loan settlement",
  "Best Advocate | Best Lawyers in Subarnapur for Loan settlement",

  "Best Advocate | Best Lawyers in Gurugram Sector 23 for Loan settlement",
  "Best Advocate | Best Lawyers in Gurugram Sector 21 for Loan settlement",
  "Best Advocate | Best Lawyers in Bengaluru Urban for Loan settlement",
  "Best Advocate | Best Lawyers in Kulgam for Loan settlement",
  "Best Advocate | Best Lawyers in Virudhunagar for Loan settlement",
  "Best Advocate | Best Lawyers in Pithoragarh for Loan settlement",
  "Best Advocate | Best Lawyers in Anand Vihar Depot for Loan settlement",
  "Best Advocate | Best Lawyers in Badarpur Border for Loan settlement",
  "Best Advocate | Best Lawyers in Balangir for Loan settlement",
  "Best Advocate | Best Lawyers in Mohan Nagar for Loan settlement",

  "Best Advocate | Best Lawyers in Albany for Loan settlement",
  "Best Advocate | Best Lawyers in Rajgarh for Loan settlement",
  "Best Advocate | Best Lawyers in Siddharth Vihar for Loan settlement",
  "Best Advocate | Best Lawyers in Sector Chi 4 for Loan settlement",
  "Best Advocate | Best Lawyers in Jalgaon for Loan settlement",
  "Best Advocate | Best Lawyers in Nalanda for Loan settlement",
  "Best Advocate | Best Lawyers in Kishanganj for Loan settlement",
  "Best Advocate | Best Lawyers in Assam for Loan settlement",
  "Best Advocate | Best Lawyers in Kondagaon for Loan settlement",
  "Best Advocate | Best Lawyers in Purnia for Loan settlement"
];
